webtalk_init -webtalk_dir /home/sohail/Desktop/project/aamir_hw/verilog/project/puf_65_imse/sim/xsim/post_impl/func/xsim.dir/puf_65_imse/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 26 19:56:42 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174149442_177724573_210753846_501" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "211ae4d9-a3ed-4b46-bfa9-4ec580a8e560" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d96ba55d-694c-4d7d-9bed-cfaa0f1d59a9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2500.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "16" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "69 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "10 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "216" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "65" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver xilinxcorelib_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "294020_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4146126834 -regid "174149442_177724573_210753846_501" -xml /home/sohail/Desktop/project/aamir_hw/verilog/project/puf_65_imse/sim/xsim/post_impl/func/xsim.dir/puf_65_imse/webtalk/usage_statistics_ext_xsim.xml -html /home/sohail/Desktop/project/aamir_hw/verilog/project/puf_65_imse/sim/xsim/post_impl/func/xsim.dir/puf_65_imse/webtalk/usage_statistics_ext_xsim.html -wdm /home/sohail/Desktop/project/aamir_hw/verilog/project/puf_65_imse/sim/xsim/post_impl/func/xsim.dir/puf_65_imse/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
