
####################################################################################
# Generated by Vivado 2021.1 built on 'Thu Jun 10 19:36:07 MDT 2021' by 'xbuild'
# Command Used: write_xdc -no_fixed_only -force ../../constraints/puf_ro_65_10_post_route.xdc
####################################################################################


####################################################################################
# Constraints from file : 'puf_ro_65_10.xdc'
####################################################################################

#define virtual clock for timing analysis

# create_clock -name clk_virt -period 4

create_clock -period 4.000 -name clk -waveform {0.000 2.000} [get_ports clk]
set_input_delay -clock [get_clocks clk] -rise 0.100 [get_ports i_en]
set_input_delay -clock [get_clocks clk] -rise 0.100 [get_ports rst_n]
set_output_delay -clock [get_clocks clk] -rise 0.200 [get_ports o_valid]
set_output_delay -clock [get_clocks clk] -rise 0.200 [get_ports o_count]
set_output_delay -clock [get_clocks clk] -rise 0.200 [get_ports o_count_set]


# Vivado Generated physical constraints 

set_property BEL BUFG [get_cells clk_IBUF_BUFG_inst]
set_property BEL INBUF_EN [get_cells clk_IBUF_inst]
set_property BEL INBUF_EN [get_cells i_en_IBUF_inst]
set_property BEL A6LUT [get_cells {i_puf_cntr/o_count[0]_i_1}]
set_property BEL A5LUT [get_cells {i_puf_cntr/o_count[1]_i_1}]
set_property BEL A6LUT [get_cells {i_puf_cntr/o_count[2]_i_1}]
set_property BEL A5LUT [get_cells {i_puf_cntr/o_count[3]_i_1}]
set_property BEL B6LUT [get_cells {i_puf_cntr/o_count[4]_i_1}]
set_property BEL AFF [get_cells {i_puf_cntr/o_count_reg[0]}]
set_property BEL A5FF [get_cells {i_puf_cntr/o_count_reg[1]}]
set_property BEL AFF [get_cells {i_puf_cntr/o_count_reg[2]}]
set_property BEL A5FF [get_cells {i_puf_cntr/o_count_reg[3]}]
set_property BEL BFF [get_cells {i_puf_cntr/o_count_reg[4]}]
set_property BEL C6LUT [get_cells i_puf_cntr/o_valid_i_1]
set_property BEL A6LUT [get_cells i_puf_cntr/o_valid_i_2]
set_property BEL AFF [get_cells i_puf_cntr/o_valid_reg]
set_property BEL B5FF [get_cells i_puf_cntr/o_valid_reg_lopt_replica]
set_property BEL A6LUT [get_cells i_puf_ro/w_nand_inferred_i_1]
set_property BEL A6LUT [get_cells {i_puf_ro/w_ring[0]_inferred_i_1}]
set_property BEL A6LUT [get_cells {i_puf_ro/w_ring[1]_inferred_i_1}]
set_property BEL A6LUT [get_cells {i_puf_ro/w_ring[2]_inferred_i_1}]
set_property BEL B6LUT [get_cells {i_puf_ro/w_ring[3]_inferred_i_1}]
set_property BEL C6LUT [get_cells {i_puf_ro/w_ring[4]_inferred_i_1}]
set_property BEL D6LUT [get_cells {i_puf_ro/w_ring[5]_inferred_i_1}]
set_property BEL B6LUT [get_cells {i_puf_ro/w_ring[6]_inferred_i_1}]
set_property BEL C6LUT [get_cells {i_puf_ro/w_ring[7]_inferred_i_1}]
set_property BEL D6LUT [get_cells {i_puf_ro/w_ring[8]_inferred_i_1}]
set_property BEL OUTBUF [get_cells {o_count_OBUF[0]_inst}]
set_property BEL OUTBUF [get_cells {o_count_OBUF[1]_inst}]
set_property BEL OUTBUF [get_cells {o_count_OBUF[2]_inst}]
set_property BEL OUTBUF [get_cells {o_count_OBUF[3]_inst}]
set_property BEL OUTBUF [get_cells {o_count_OBUF[4]_inst}]
set_property BEL OUTBUF [get_cells {o_count_set_OBUF[0]_inst}]
set_property BEL OUTBUF [get_cells {o_count_set_OBUF[1]_inst}]
set_property BEL OUTBUF [get_cells {o_count_set_OBUF[2]_inst}]
set_property BEL OUTBUF [get_cells {o_count_set_OBUF[3]_inst}]
set_property BEL OUTBUF [get_cells {o_count_set_OBUF[4]_inst}]
set_property BEL OUTBUF [get_cells o_valid_OBUF_inst]
set_property BEL AFF [get_cells reg_ro_reg]
set_property BEL INBUF_EN [get_cells rst_n_IBUF_inst]
set_property LOC BUFGCTRL_X0Y0 [get_cells clk_IBUF_BUFG_inst]
set_property LOC L22 [get_cells clk_IBUF_inst]
set_property LOC R18 [get_cells i_en_IBUF_inst]
set_property LOC SLICE_X0Y103 [get_cells {i_puf_cntr/o_count[0]_i_1}]
set_property LOC SLICE_X0Y103 [get_cells {i_puf_cntr/o_count[1]_i_1}]
set_property LOC SLICE_X0Y104 [get_cells {i_puf_cntr/o_count[2]_i_1}]
set_property LOC SLICE_X0Y104 [get_cells {i_puf_cntr/o_count[3]_i_1}]
set_property LOC SLICE_X0Y104 [get_cells {i_puf_cntr/o_count[4]_i_1}]
set_property LOC SLICE_X0Y103 [get_cells {i_puf_cntr/o_count_reg[0]}]
set_property LOC SLICE_X0Y103 [get_cells {i_puf_cntr/o_count_reg[1]}]
set_property LOC SLICE_X0Y104 [get_cells {i_puf_cntr/o_count_reg[2]}]
set_property LOC SLICE_X0Y104 [get_cells {i_puf_cntr/o_count_reg[3]}]
set_property LOC SLICE_X0Y104 [get_cells {i_puf_cntr/o_count_reg[4]}]
set_property LOC SLICE_X0Y104 [get_cells i_puf_cntr/o_valid_i_1]
set_property LOC SLICE_X0Y101 [get_cells i_puf_cntr/o_valid_i_2]
set_property LOC SLICE_X1Y104 [get_cells i_puf_cntr/o_valid_reg]
set_property LOC SLICE_X0Y104 [get_cells i_puf_cntr/o_valid_reg_lopt_replica]
set_property LOC SLICE_X1Y100 [get_cells i_puf_ro/w_nand_inferred_i_1]
set_property LOC SLICE_X0Y100 [get_cells {i_puf_ro/w_ring[0]_inferred_i_1}]
set_property LOC SLICE_X1Y99 [get_cells {i_puf_ro/w_ring[1]_inferred_i_1}]
set_property LOC SLICE_X0Y99 [get_cells {i_puf_ro/w_ring[2]_inferred_i_1}]
set_property LOC SLICE_X0Y99 [get_cells {i_puf_ro/w_ring[3]_inferred_i_1}]
set_property LOC SLICE_X0Y99 [get_cells {i_puf_ro/w_ring[4]_inferred_i_1}]
set_property LOC SLICE_X0Y99 [get_cells {i_puf_ro/w_ring[5]_inferred_i_1}]
set_property LOC SLICE_X0Y100 [get_cells {i_puf_ro/w_ring[6]_inferred_i_1}]
set_property LOC SLICE_X0Y100 [get_cells {i_puf_ro/w_ring[7]_inferred_i_1}]
set_property LOC SLICE_X0Y100 [get_cells {i_puf_ro/w_ring[8]_inferred_i_1}]
set_property LOC T23 [get_cells {o_count_OBUF[0]_inst}]
set_property LOC R22 [get_cells {o_count_OBUF[1]_inst}]
set_property LOC T22 [get_cells {o_count_OBUF[2]_inst}]
set_property LOC P26 [get_cells {o_count_OBUF[3]_inst}]
set_property LOC R26 [get_cells {o_count_OBUF[4]_inst}]
set_property LOC T25 [get_cells {o_count_set_OBUF[0]_inst}]
set_property LOC T24 [get_cells {o_count_set_OBUF[1]_inst}]
set_property LOC M26 [get_cells {o_count_set_OBUF[2]_inst}]
set_property LOC N26 [get_cells {o_count_set_OBUF[3]_inst}]
set_property LOC P25 [get_cells {o_count_set_OBUF[4]_inst}]
set_property LOC R25 [get_cells o_valid_OBUF_inst]
set_property LOC SLICE_X0Y101 [get_cells reg_ro_reg]
set_property LOC R23 [get_cells rst_n_IBUF_inst]
set_property PACKAGE_PIN L22 [get_ports clk]
set_property PACKAGE_PIN R18 [get_ports i_en]
set_property PACKAGE_PIN T23 [get_ports {o_count[0]}]
set_property PACKAGE_PIN R22 [get_ports {o_count[1]}]
set_property PACKAGE_PIN T22 [get_ports {o_count[2]}]
set_property PACKAGE_PIN P26 [get_ports {o_count[3]}]
set_property PACKAGE_PIN R26 [get_ports {o_count[4]}]
set_property PACKAGE_PIN T25 [get_ports {o_count_set[0]}]
set_property PACKAGE_PIN T24 [get_ports {o_count_set[1]}]
set_property PACKAGE_PIN M26 [get_ports {o_count_set[2]}]
set_property PACKAGE_PIN N26 [get_ports {o_count_set[3]}]
set_property PACKAGE_PIN P25 [get_ports {o_count_set[4]}]
set_property PACKAGE_PIN R25 [get_ports o_valid]
set_property PACKAGE_PIN R23 [get_ports rst_n]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
