${PROJ_DIR}/dut/rtl/puf_soc_sipo.v
${PROJ_DIR}/dut/rtl/puf_soc_ro_decoder.v
${PROJ_DIR}/dut/rtl/puf_soc_ro_not.v
${PROJ_DIR}/dut/rtl/puf_soc_ro.v
${PROJ_DIR}/dut/rtl/puf_soc_ro_bank.v
${PROJ_DIR}/dut/rtl/puf_soc_mux.v
${PROJ_DIR}/dut/rtl/puf_soc_counter.v
${PROJ_DIR}/dut/rtl/puf_soc_piso.v
${PROJ_DIR}/dut/rtl/puf_soc_comparator.v
${PROJ_DIR}/dut/rtl/puf_soc_assembler.v
${PROJ_DIR}/dut/rtl/puf_soc_cntrlr.v
${PROJ_DIR}/dut/rtl/puf_soc_dta_pth.v
${PROJ_DIR}/dut/rtl/puf_soc_top.v