add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_0
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_1
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_2
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_3
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_4
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_5
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_6
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_7
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_8
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_9
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_10
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_11
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_12
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_13
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_14
add wave -position insertpoint sim:/tb_puf_soc_mux/i_data_15
add wave -position insertpoint sim:/tb_puf_soc_mux/i_sel_mux
add wave -position insertpoint sim:/tb_puf_soc_mux/o_mux    